name: Create GitHub release for new tag
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Github Release"
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          prerelease: false